# Generated by Django 5.2.7 on 2025-10-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="share_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
